# Project settings for execute.py
players:
  - kyxsan
  - m0NESY
  - TeSeS
  - kyousuke
  - NiKo
  - molodoy
  - KSCERATO
  - YEKINDAR
  - yuurih
  - FalleN

types:
  - mouse
  - keyboard
  - combined

actions:
  model:
    - train

  dataset:
    - extract # 提取特征
    - convert # 转换为pt
    - manifest # 生成manifest文件
    - freeze # 冻结数据，便于复制

  pre:
    - discretize # 确定离散化分布，预处理，执行一次后无需重复

overlap-ratio: 0.0
time-window: 640
fold: 10

path:
  demos: "d:\\Project\\cs2_parser\\demoparser\\demo_file"

  origin: "d:\\Project\\Research\\dataset\\origin_data"
  mouse: "d:\\Project\\Research\\dataset\\origin_data\\mouse_data_f_f"
  keyboard: "d:\\Project\\Research\\dataset\\origin_data\\keyboard_data_f_f"
  time: "d:\\Project\\Research\\dataset\\origin_data\\time_data_f_f"

  extract: "d:\\Project\\Research\\dataset\\extracted_data_f_f"
  pt: "d:\\Project\\Research\\dataset\\pt_data"

  output: "d:\\Project\\Research\\output"
  result: "d:\\Project\\Research\\result"

model:
  player: "FalleN"
  type: "keyboard"
  arch: "gru"
  epochs: 100
  bsz: 128
  lr: 0.001
  weight-decay: 0.00001
  hidden-dim: 64
  num-layers: 2
  dropout: 0.3
  patience: 10
  use-attention: true
  workers: 0 # Set to 0 when using RAM cache

way: "model" # "model" or "dataset" or "all"
task: "identification" # "authentication" or "identification"

defaults:
  parallel: 1
  verbose: false
  # add other defaults as needed, e.g., steps: [extract, convert, freeze, train]